student/urls.py
from django.urls import path
from .views import index, add_and_edit, delete

app_name = 'student'

urlpatterns = [
    path('', index, name='index'),
    path('add/', add_and_edit, name='add'),
    path('edit/<int:pk>/', add_and_edit, name='edit'),
    path('delete/<int:pk>/', delete, name='delete'),

]

user/urls.py
from django.urls import path
from .views import index, add_and_edit

app_name = 'user'

urlpatterns = [
    path('', index, name='index'),
    path('add/', add_and_edit, name='add'),
    path('edit/<int:pk>/', add_and_edit, name='edit'),

]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from dashboard.views import log_in, log_out
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', log_in, name=''),
    path('logout/', log_out, name='logout'),
    path('student/', include('student.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('teacher/', include('teacher.urls')),
    path('user/', include('user.urls')),
    path("report/", include("report.urls")),

]

student/models.py
from django.db import models


# Create your models here.

class Student(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=100)
    register = models.CharField(max_length=30, unique=True)
    birth_date = models.DateField()
    classroom = models.CharField(max_length=20)
    phone = models.CharField(unique=True, blank=True, max_length=10)
    city = models.CharField(max_length=20)
    gender = models.BooleanField()

    def __str__(self):
        return f"{self.last_name} - {self.first_name}"

    class Meta:
        verbose_name = "Eleve"
        verbose_name_plural = "Eleves"

student/forms.py
from django import forms
from .models import Student

CLASS = [
    ('', ' Selectionnez une classe'),
    ('Tle', 'Tle'),
    ('1ère', '1ère'),
    ('2nd', '2nd'),
    ('3ème', '3ème'),
    (' 4ème', '4ème'),
    ('5ème', '5ème'),
    ('6ème', '6ème')
]

GENDER = [
    (True, 'Homme'),
    (False, 'Femme')
]

# class StudentForm(forms.Form):
#     CLASS = [
#         (' Selectionnez une classe', ' Selectionnez une classe'),
#         ('Tle', 'Tle'),
#         ('1ère', '1ère'),
#         ('2nd', '2nd'),
#         ('3ème', '3ème'),
#         (' 4ème', '4ème'),
#         ('5ème', '5ème'),
#         ('6ème', '6ème')
#     ]
#     GENDER = [
#         ('0', 'Homme'),
#         ('1', 'Femme')
#     ]
#     first_name = forms.CharField(required=True)
#     last_name = forms.CharField(widget=forms.TextInput(
#         attrs={
#             'placeholder': 'MON NOM',
#             'class':'name'

#         }
#     ))
#     birth_date = forms.DateField(widget=forms.DateInput(
#         attrs={
#             'type':'date',
#             'placeholder':'Date of Birth',

#         }
#     ))
#     classroom = forms.ChoiceField(choices=CLASS)
#     phone = forms.CharField(widget=forms.NumberInput(
#         attrs={
#             'min':'1',
#             'placeholder':'Number'
#         }))
#     city = forms.CharField(max_length=20,widget=forms.TextInput(
#         attrs={
#             'placeholder':'City'
#         }
#     ))
#     register = forms.CharField(widget=forms.TextInput(
#         attrs={
#             'placeholder':'Register'
#         }

#     ))
#     gender = forms.ChoiceField(choices=GENDER, widget=forms.RadioSelect())

gender = forms.BooleanField(widget=forms.RadioSelect(choices=GENDER))


class StudentForm(forms.ModelForm):
    # def __init__(self, *args, **kwargs):
    #     super(StudentForm,self).__init__(*args, **kwargs)
    #     instance = kwargs.get('instance')
    #     if instance:
    #         if instance.gender == 0:
    #             self.fields['gender'].initial = 0
    #         self.fields['gender'].initial = 1

    class Meta:
        model = Student
        fields = ['first_name', 'last_name', 'birth_date', 'classroom', 'phone', 'city', 'register', 'gender']
        widgets = {
            'first_name': forms.TextInput(attrs={'placeholder': 'First Name'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Last Name'}),
            'birth_date': forms.DateInput(attrs={'type': 'date', 'placeholder': 'Date of Birth'}),
            'classroom': forms.Select(choices=CLASS, attrs={'placeholder': 'Classroom'}),
            'phone': forms.NumberInput(attrs={'min': '1', 'placeholder': 'Number'}),
            'city': forms.TextInput(attrs={'placeholder': 'City'}),
            'register': forms.TextInput(attrs={'placeholder': 'Register'}),
            'gender': forms.RadioSelect(choices=GENDER),
        }

student/views.py
from django.shortcuts import render, get_object_or_404, redirect

from .forms import StudentForm
from .models import Student
from datetime import datetime
from django.contrib.auth.decorators import login_required



# Create your views here.

@login_required
def index(request):
    students = Student.objects.all()
    today = datetime.now().year

    context = {
        'students': students,
        'today': today,
    }
    return render(request, "student/list.html", context)



@login_required
def add_and_edit(request, pk=None):
    if pk:
        student = get_object_or_404(Student, id=pk)
    else:
        student = None
    if request.method == 'POST':
        form = StudentForm(request.POST, instance=student)
        if form.is_valid():
            form.save()
            return redirect('student:index')

    form = StudentForm(instance=student)
    context = {
        'form': form
    }
    return render(request, "student/forms.html", context)


# def edit(request, id):
#     return render(request, "student/student_edit.html")


def delete(request, pk):
    student = get_object_or_404(Student, id=pk)
    student.delete()
    return redirect('student:index')

templates/student/forms.html
{% extends 'base.html' %}
{% load static %}

{% block title %}<title>Mon Etab - {% if form.instance.pk is  None %}Ajouter{% else %}Modifier{% endif %} un Élève</title> {% endblock %}
{% block content %}

    <main>
        <a href="{% url 'student:index' %}" class="return"><i class="fas fa-arrow-left"></i>Retour</a>

        <form method="post">
            {% csrf_token %}
            <h2>{% if form.instance.pk is not None %}Modifier un élève{% else %}Ajouter un élève{% endif %}</h2>
            <div>
                {{ form.last_name }}
                {{ form.classroom }}
            </div>
            <div>
                {{ form.first_name }}
                {{ form.phone }}
            </div>
            <div>
                {{ form.gender }}
            </div>
            <div>
                {{ form.register }}
                {{ form.city }}
            </div>
            <div style="grid-column: span 1">
                {{ form.birth_date }}
            </div>
            <div>
                {% if form.instance.pk is  None %}<button type="reset" style="background-color: red;" >Annuler</button>{% endif %}
                <button type="submit">{% if form.instance.pk is  None %} Enregistrer{% else %} Enregistrer modification {% endif %}</button>
            </div>

        </form>
    </main>
{% endblock %}

templates/student/list.html
{% extends 'base.html' %}
{% load static %}
{% load mathfilters %}


{% block title %}    <title>Mon Etab - Élèves</title> {% endblock %}

{% block content %}

    <main class="machin">
        <h2>Élèves ({{total_students}})</h2>
        <a href="{% url 'student:add' %}" style=" text-decoration: none; color: black;position: absolute; top: 1rem; right: 3rem;">
            <i class="fa-solid fa-circle-plus"></i>Nouveau élève
        </a>
        {% if students %}
            <table id="table">
                <thead>
                <tr>
                    <th>Nom </th>
                    <th>Prénom</th>
                    <th>Classe</th>
                    <th>Matricule</th>
                    <th>Âge</th>
                    <th>Téléphone</th>
                    <th>Ville</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    {% for student in students %}
                        <td>{{student.first_name}}</td>
                        <td>{{student.last_name}}</td>
                        <td>{{student.classroom}}</td>
                        <td>{{student.register}}</td>
                        <td>{{today|sub:student.birth_date.year}}</td>
                        <td>{{student.phone}}</td>
                        <td>{{student.city}}</td>
                        <td><a href="{% url 'student:edit' pk=student.id %}"><button type="button" style="background-color: orangered; color: black;">Modifier</button></a> <button class="deleteButton" data-url="{% url 'student:delete' pk=student.id %}" style="background-color: red; color: black;">Supprimer</button></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            0 élève enregistré
        {% endif %}

    </main>


    <div class="alert">
        <p>ATTENTION !!</p>
        <p>Voulez-vous vraiment supprimer cet éleve?</p>
        <button id="confirmDelete" >Oui</button>
        <button id="cancelDelete">Non</button>
    </div>
{% endblock %}