teacher/urls.py
from django.urls import path
from .views import index, add_and_edit, delete

app_name = 'teacher'

urlpatterns = [
    path('', index, name='index'),
    path('add/', add_and_edit, name='add'),
    path('edit/<int:pk>/', add_and_edit, name='edit'),
    path('delete/<int:pk>/', delete, name='delete'),

]

user/urls.py
from django.urls import path
from .views import index, add_and_edit

app_name = 'user'

urlpatterns = [
    path('', index, name='index'),
    path('add/', add_and_edit, name='add'),
    path('edit/<int:pk>/', add_and_edit, name='edit'),

]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from dashboard.views import log_in, log_out
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', log_in, name=''),
    path('logout/', log_out, name='logout'),
    path('student/', include('student.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('teacher/', include('teacher.urls')),
    path('user/', include('user.urls')),
    path("report/", include("report.urls")),

]

teacher/models.py
from django.db import models


# Create your models here.
class Teacher(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=100)
    birth_date = models.DateField()
    subject_taught = models.CharField(max_length=20)
    next_class = models.CharField(max_length=50, null=True, blank=True)
    next_meeting_topic = models.CharField(max_length=100, null=True, blank=True)
    phone = models.CharField(unique=True, blank=True, max_length=10)
    city = models.CharField(max_length=20)
    gender = models.BooleanField()
    vacant = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.first_name} - {self.last_name}"

    class Meta:
        verbose_name = "Profeseur"
        verbose_name_plural = "Professeurs"

teacher/forms.py
from django import forms
from .models import Teacher

MATTER = [
    ('', ' Selectionnez une matière'),
    ('Math', 'Math'),
    ('Physique', 'Physique'),
    ('EPS', 'EPS'),
    ('Anglais', 'Anglais'),
    ('SVT', 'SVT'),
    ('Philosophie', 'Philosophie'),
    ('Français', 'Français')
]
GENDER = [
    (True, 'Homme'),
    (False, 'Femme')
]


# class TeacherForm(forms.Form):
#     MATTER = [
#         (' Selectionnez une matière', ' Selectionnez une matière'),
#         ('Math', 'Math'),
#         ('Physique', 'Physique'),
#         ('EPS', 'EPS'),
#         ('Anglais', 'Anglais'),
#         (' SVT', 'SVT'),
#         ('Philosophie', 'Philosophie'),
#         ('Français', 'Français')
#     ]
#     GENDER = [
#         (True, 'Homme'),
#         (False, 'Femme')
#     ]
#     first_name = forms.CharField(required=True, widget=forms.TextInput(
#         attrs={
#             'placeholder': 'First name'
#         }))
#     last_name = forms.CharField(widget=forms.TextInput(
#         attrs={
#             'placeholder': 'Last name'
#         }
#     ))
#     birth_date = forms.DateField(widget=forms.DateInput(
#         attrs={
#             'type':'date',
#
#         }
#     ))
#     matter = forms.ChoiceField(choices=MATTER)
#     phone = forms.CharField(widget=forms.NumberInput(
#         attrs={
#             'min':'1',
#             'placeholder':'Number'
#         }))
#     city = forms.CharField(max_length=20,widget=forms.TextInput(
#         attrs={
#             'placeholder':'City'
#         }
#     ))
#     gender = forms.ChoiceField(choices=GENDER, widget=forms.RadioSelect())

class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = ['first_name', 'last_name', 'birth_date', 'subject_taught', 'phone', 'city', 'gender']
        widgets = {
            'first_name': forms.TextInput(attrs={'placeholder': 'First Name'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Last Name'}),
            'birth_date': forms.DateInput(attrs={'type': 'date', 'placeholder': 'Date of Birth'}),
            'subject_taught': forms.Select(choices=MATTER),
            'phone': forms.NumberInput(attrs={'min': '1', 'placeholder': 'Number'}),
            'city': forms.TextInput(attrs={'placeholder': 'City'}),
            'gender': forms.RadioSelect(choices=GENDER),
        }

teacher/views.py
from django.shortcuts import render, redirect, get_object_or_404
from datetime import datetime
from .forms import TeacherForm
from .models import Teacher
from django.contrib.auth.decorators import login_required



# Create your views here.
@login_required
def index(request):
    teachers = Teacher.objects.all()
    today = datetime.now().year
    numbers_teacher = teachers.count()
    context = {
        'teachers': teachers,
        'total': numbers_teacher,
        'today': today,
    }
    return render(request, "teacher/list.html", context)


@login_required
def add_and_edit(request, pk=None):
    if pk:
        teacher = get_object_or_404(Teacher, id=pk)
    else:
        teacher = None
    if request.method == "POST":
        form = TeacherForm(request.POST, instance=teacher)
       
        if form.is_valid():
            form.save()
            return redirect('teacher:index')
    form = TeacherForm(instance=teacher)
    context = {
        'form': form
    }
    return render(request, "teacher/forms.html", context)


# def edit(request, pk):
#     pass


def delete(request, pk):
    teacher = get_object_or_404(Teacher, id=pk)
    teacher.delete()
    return redirect('teacher:index')

templates/teacher/forms.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Mon Etab - {% if form.instance.pk is  None %}Ajouter{% else %}Modifier{% endif %} Professeur</title>
{% endblock %}
{% block content %}

        <main>
            <a href="{% url 'teacher:index' %}" class="return"><i class="fas fa-arrow-left"></i>Retour</a>

            <h2>{% if form.instance.pk is not None %}Modifier professeur {% else %} Ajouter professeur{% endif %}</h2>
            <form method="post">
                {% csrf_token %}
                <div>
                    {{ form.last_name }}
                    {{ form.subject_taught }}

                </div>
                <div>
                    {{ form.first_name }}
                    {{ form.phone }}

                </div>
                <div>
                    {{ form.gender }}
                </div>
                <div>
                    {{ form.birth_date }}
                    {{ form.city }}
                </div>  
                <div>
                    {% if form.instance.pk is  None %}<button type="reset" style="background-color: red;" >Annuler</button>{% endif %}
                    <button type="submit">{% if form.instance.pk is  None %} Enregistrer{% else %} Enregistrer modification {% endif %}</button>
                </div>
            </form>
        </main>
{% endblock %}

templates/teacher/list.html
{% extends 'base.html' %}
{% load static %}
{% load mathfilters %}

{% block title %}<title>Mon Etab - Professeurs</title> {% endblock %}

{% block content %}

    <main class="machin">
        <h2>Professeurs ({{ total_teachers }})</h2>
        <a href="{% url 'teacher:add' %}" style=" text-decoration: none; color: black;position: absolute; top: 1rem; right: 3rem;">
            <i class="fa-solid fa-circle-plus"></i>Nouveau professeur
        </a>
    {% if teachers %}
        <table id="table">
            <thead>
            <tr>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Matière</th>
                <th>Vacant</th>
                <th>Âge</th>
                <th>Téléphone</th>
                <th>Ville</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for teacher in teachers %}
            <tr>
                <td>{{ teacher.last_name }}</td>
                <td>{{ teacher.first_name }}</td>
                <td>{{ teacher.subject_taught }}</td>
                <td>{% if teacher.vacant == True %}Oui{% else %}Non{% endif %}</td>
                <td>{{ today |sub:teacher.birth_date.year  }}</td>
                <td>{{ teacher.phone }}</td>
                <td>{{  teacher.city }}</td>
                <td><a href="{% url 'teacher:edit' pk=teacher.id %}"><button type="button" style="background-color: orangered; color: black;">Modifier</button></a> 
                    <button class="deleteButton"  data-url="{% url 'teacher:delete' pk=teacher.id %}" style="background-color: red; color: black;">Supprimer</button></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
    0 professeur enregistré
    {% endif %}
    </main>
    <div class="alert">
        <p>ATTENTION !!</p>
        <p>Voulez-vous vraiment supprimer cet professeur?</p>
        <button id="confirmDelete">Oui</button>
        <button id="cancelDelete">Non</button>
    </div>
{% endblock %}