dashboard/urls.py
from django.urls import path
from .views import index

app_name = 'dashboard'

urlpatterns = [
    path('', index, name='index'),
]

report/urls.py
from django.urls import path
from .views import index

app_name = 'report'

urlpatterns = [
    path('', index, name='index'),
]

student/urls.py
from django.urls import path
from .views import index, add_and_edit, delete

app_name = 'student'

urlpatterns = [
    path('', index, name='index'),
    path('add/', add_and_edit, name='add'),
    path('edit/<int:pk>/', add_and_edit, name='edit'),
    path('delete/<int:pk>/', delete, name='delete'),

]

teacher/urls.py
from django.urls import path
from .views import index, add_and_edit, delete

app_name = 'teacher'

urlpatterns = [
    path('', index, name='index'),
    path('add/', add_and_edit, name='add'),
    path('edit/<int:pk>/', add_and_edit, name='edit'),
    path('delete/<int:pk>/', delete, name='delete'),

]

user/urls.py
from django.urls import path
from .views import index, add_and_edit

app_name = 'user'

urlpatterns = [
    path('', index, name='index'),
    path('add/', add_and_edit, name='add'),
    path('edit/<int:pk>/', add_and_edit, name='edit'),

]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from dashboard.views import log_in, log_out
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', log_in, name=''),
    path('logout/', log_out, name='logout'),
    path('student/', include('student.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('teacher/', include('teacher.urls')),
    path('user/', include('user.urls')),
    path("report/", include("report.urls")),

]

base/models.py
from django.db import models

# Create your models here.

base/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}<title>t</title> {% endblock %}
    <link rel="stylesheet" href={% static "css/style.css" %}>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/2.5.1/uicons-regular-straight/css/uicons-regular-straight.css'>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.5/css/jquery.dataTables.min.css">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    {#    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.5/css/jquery.dataTables.min.css">#}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.5/js/jquery.dataTables.min.js"></script>


</head>
<body>
<div class="dashboard">
    {% include 'menu.html' %}

    {% block content %}

    {% endblock %}
</div>

</body>
{% include 'scripts.html' %}
</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mon Etab - Connexion</title>
    <link rel="stylesheet" href={% static 'css/style.css' %}>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">

</head>
<body>
<div class="login-container">
    <div class="login-box">
        <h1><i class="fas fa-leaf"></i>Mon Etab</h1>
        <form method="post">
            {% csrf_token %}
        <div>{{  form.username }}</div>
    <div> {{  form.password }}</div>
     {% if messages %}
        {% for m in messages %}
            <h3>{{m}}</h3>
        {% endfor %}
     {% endif %}
        

        
       <div><button type="submit">Connexion</button></div> 
        </form>
    </div>
</div>
</body>
</html>

templates/menu.html
<aside>
    {% url 'dashboard:index'  as dashboard_url %}
    {% url 'student:index'  as eleve_url %}
    {% url 'student:add'  as eleve_add_url %}
    {% url 'student:edit'  as eleve_edit_url %}
    
    {% url 'teacher:index'  as professeur_url %}
    {% url 'teacher:add'  as professeur_add_url %}
    {% url 'teacher:edit'  as professeur_edit_url %}
    {% url 'user:index'  as utilisateur_url %}
    {% url 'user:edit'  as utilisateur_edit_url %}
    {% url 'report:index'  as rapport_url %}

    <h2><i class="fas fa-leaf"></i>Mon Etab</h2>
    <nav>
        <ul>
            
            <li {% if request.path == dashboard_url %} class="active text-active" {% endif %}><i class="fas fa-grip-horizontal"> </i><a href="{% url 'dashboard:index' %}"> Tableau de bord </a></li>
            <li {% if request.path == eleve_url  or request.path == eleve_edit_url or request.path == eleve_add_url %} class="active text-active" {% endif %}><i class="fi fi-rs-users-class"></i><a href={% url 'student:index' %}> Élèves</a></li>
            <li {% if request.path == professeur_url or request.path == professeur_add_url or request.path == professeur_edit_url %} class="active text-active" {% endif %}><i class="fas fa-chalkboard-teacher"></i><a href={% url 'teacher:index' %}> Professeurs</a></li>
            <li {% if request.path == utilisateur_url or request.path == utilisateur_edit_url %} class="active text-active" {% endif %}><i class="fa-regular fa-user"></i> <a href={% url 'user:index' %}> Utilisateurs</a></li>
            <li {% if request.path == rapport_url %} class="active text-active" {% endif %}><i class="fas fa-file-alt"></i><a href={% url 'report:index' %}> Rapport</a></li>

        </ul>
    </nav>
    <h5 style="color: blue;">{{user.username|upper}}</h5>
    <a href={% url 'logout' %}>
        <i class="fa-solid fa-arrow-right-from-bracket"></i>Déconnexion
    </a>
</aside>

templates/scripts.html
{% load static %}

<script src= {% static "js/graph.js" %}></script>
<script src= {% static "js/dataTable.js" %}></script>
<script src= {% static "js/modal.js" %}></script>