user/urls.py
from django.urls import path
from .views import index, add_and_edit

app_name = 'user'

urlpatterns = [
    path('', index, name='index'),
    path('add/', add_and_edit, name='add'),
    path('edit/<int:pk>/', add_and_edit, name='edit'),

]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from dashboard.views import log_in, log_out
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', log_in, name=''),
    path('logout/', log_out, name='logout'),
    path('student/', include('student.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('teacher/', include('teacher.urls')),
    path('user/', include('user.urls')),
    path("report/", include("report.urls")),

]

user/models.py
from django.db import models


# Create your models here.
class User(models.Model):
    pseudo = models.CharField(max_length=20, unique=True)
    password = models.CharField(max_length=15)
    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.pseudo

    class Meta:
        verbose_name = "Utilisateur"
        verbose_name_plural = "Utilisateurs"

user/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        # instance = kwargs.get('instance')
        # if instance is not None:
        #     self.fields['pseudo'].widget.attrs.update({
        #         'hidden': True,
        #         'label': ''
        #     })
        self.fields['username'].help_text = ''

    class Meta:
        model = User
        fields = ["username", "password"]
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your username'},),
            'password': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter your password'}),
        }

user/views.py
from django.shortcuts import render, redirect, get_object_or_404

from .forms import UserForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


# Create your views here.
@login_required
def index(request):
    users = User.objects.all()
    numbers_users = users.count()
    context = {
        'users': users,
        'total': numbers_users,
    }
    return render(request, "user/list.html", context)


@login_required
def add_and_edit(request, pk=None):
    if pk:
        user = get_object_or_404(User, id=pk)
    else:
        user = None

    if request.method == "POST":
        user_form = UserForm(request.POST, instance=user)

        if user_form.is_valid():
            user = user_form.save(commit=False)  
            password = request.POST.get('password', '')
            if password:  
                user.set_password(password)
            user.save()  
            return redirect('user:index')
        else:
            return render(request, 'user/forms.html', {"form": user_form})
    
    user_form = UserForm(instance=user)
    context = {
        "form": user_form
    }
    return render(request, "user/forms.html", context)

# def edit(request, id):
#   return render(request, "user/users_edit.html")

templates/user/forms.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>Mon Etab - {% if form.instance.pk is  None %}Ajouter{% else %}Modifier{% endif %} Utilisateur</title>
{% endblock %}

{% block content %}

    <main >
        <a href="{% url 'user:index' %}" class="return"><i class="fas fa-arrow-left"></i>Retour</a>

        <h2 style="text-align: center;">{% if form.instance.pk is  None %}Ajouter{% else %}Modifier{% endif %} utilisateur</h2>

        <form method="post">
            {% csrf_token %}
            {{ form | crispy }}
            <div>
                {% if form.instance.pk is  None %}<button type="reset" style="background-color: red;" >Annuler</button>{% endif %}
                <button type="submit">{% if form.instance.pk is  None %} Enregistrer{% else %} Enregistrer modification {% endif %}</button>
            </div>
        </form>
    </main>
{% endblock %}

templates/user/list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>Mon Etab - Utilisateurs</title>
{% endblock %}

{% block content %}


    <main>
        <h2>Utilisateurs ({{ total_users}})</h2>
        <a href="{% url 'user:add' %}" style=" text-decoration: none; color: black;position: absolute; top: 2rem; right: 3rem;">
            <i class="fa-solid fa-circle-plus"></i>Nouveau utilisateur
        </a>
        {% if users %}
            <table id="table">
                <thead>
                <tr>
                    <th>Pseudo</th>
                    <th>Date de création</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for user in users %}
                    <tr>
                        <td>{{ user.username }}</td>
                        <td>{{ user.date_joined | date:"d/m/Y" }}</td>
                        <td><a href="{% url 'user:edit' pk=user.id %}"><button type="button" style="background-color: orangered; color: black;">Modifier</button></a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            0 utilisateur enregistré
        {% endif %}
    </main>
{% endblock %}